apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines
spec:
  channel: stable
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   labels:
#     app.kubernetes.io/instance: openshift-pipelines
#     operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ""
#   name: openshift-pipelines-operator-rh
#   namespace: openshift-operators
# spec:
#   channel: stable
#   installPlanApproval: Automatic
#   name: openshift-pipelines-operator-rh
#   source: gitops-pipelines-operators
#   sourceNamespace: openshift-marketplace
#   # startingCSV: openshift-pipelines-operator-rh.v1.6.3
